// Copies the REAL extension scripts into the harness, so the test always runs
// the shipped code rather than a copy that can drift.
const fs = require("fs");
const path = require("path");

const EXT = require("path").resolve(__dirname, "../../extension");
const OUT = __dirname;

for (const f of ["shared.js", "vinted.js"]) {
  fs.copyFileSync(path.join(EXT, "content", f), path.join(OUT, f));
}

// Pull the main-world helpers out of background.js by brace matching, so the
// harness exercises the real description-filling code too.
const bg = fs.readFileSync(path.join(EXT, "background.js"), "utf8");
const wanted = [
  "_mwFillDescription", "_mwFillHiddenDescription", "_mwHiddenDescriptionValue",
  "_mwBlurDescription", "_mwEnforceDescription", "_mwNudgeDescription",
  "_mwDescribeDescriptionFields", "_mwFillBrand",
  // De verwijderroutine van Vinted. Zie vinted-delete.html: die pagina bootst
  // het echte scherm na met Vinted's eigen knopteksten en bewijst dat de
  // bevestiging in het vénster wordt aangeklikt en niet de knop op de pagina.
  "_mwVintedVerwijderen",
];
let out = "// AUTO-GENERATED by build.js — sliced verbatim out of extension/background.js\n";
for (const name of wanted) {
  const re = new RegExp(`^(async )?function ${name}\\s*\\(`, "m");
  const m = bg.match(re);
  if (!m) { console.warn("not found:", name); continue; }
  const start = m.index;
  let i = bg.indexOf("{", start), depth = 0, end = -1;
  for (; i < bg.length; i++) {
    const c = bg[i];
    if (c === "{") depth++;
    else if (c === "}") { depth--; if (depth === 0) { end = i + 1; break; } }
  }
  out += bg.slice(start, end) + "\n\n";
}
fs.writeFileSync(path.join(OUT, "mw-functions.js"), out);
console.log("harness built:", wanted.length, "main-world helpers +", 2, "content scripts");
