// Copies the REAL extension scripts into the harness, so the test always runs
// the shipped code rather than a copy that can drift.
const fs = require("fs");
const path = require("path");

const EXT = require("path").resolve(__dirname, "../../extension");
const OUT = __dirname;

for (const f of ["shared.js", "vinted.js"]) {
  fs.copyFileSync(path.join(EXT, "content", f), path.join(OUT, f));
}

const bg = fs.readFileSync(path.join(EXT, "background.js"), "utf8");

// Accolades tellen ZONDER je te laten foppen door strings, sjablonen,
// commentaar en regex-literals. Dat laatste is niet theoretisch: de
// Marktplaats-code bevat /^\s*\(([^)]{1,24})\)/ en een domme teller ziet daar
// een accolade openen die nooit sluit — dan snijdt de bouwer de halve rest van
// het bestand mee en draait de proef niet meer wat er verscheept wordt.
function sliceBody(from) { return sliceOut(bg, from); }
function sliceOut(bg, from) {
  let i = bg.indexOf("{", from), start = i, depth = 0, prev = "";
  while (i < bg.length) {
    const c = bg[i], two = bg.slice(i, i + 2);
    if (two === "//") { i = bg.indexOf("\n", i); continue; }
    if (two === "/*") { i = bg.indexOf("*/", i) + 2; continue; }
    if (c === '"' || c === "'" || c === "`") {
      const q = c; i++;
      while (i < bg.length) {
        if (bg[i] === "\\") { i += 2; continue; }
        if (bg[i] === q) break;
        i++;
      }
      i++; prev = q; continue;
    }
    if (c === "/" && (prev === "" || "(,=:[!&|?{};+~*%^<>".includes(prev))) {
      i++;
      let inClass = false;
      while (i < bg.length) {
        if (bg[i] === "\\") { i += 2; continue; }
        if (bg[i] === "[") inClass = true;
        else if (bg[i] === "]") inClass = false;
        else if (bg[i] === "/" && !inClass) break;
        else if (bg[i] === "\n") break;
        i++;
      }
      i++; prev = "/"; continue;
    }
    if (c === "{") depth++;
    else if (c === "}") { depth--; if (depth === 0) return bg.slice(start, i + 1); }
    if (!/\s/.test(c)) prev = c;
    i++;
  }
  throw new Error("geen sluitende accolade vanaf " + from);
}

const wanted = [
  "_mwFillDescription", "_mwFillHiddenDescription", "_mwHiddenDescriptionValue",
  "_mwBlurDescription", "_mwEnforceDescription", "_mwNudgeDescription",
  "_mwDescribeDescriptionFields", "_mwFillBrand",
  // De verwijderroutine van Vinted. Zie vinted-delete.html: die pagina bootst
  // het echte scherm na met Vinted's eigen knopteksten en bewijst dat de
  // bevestiging in het vénster wordt aangeklikt en niet de knop op de pagina.
  "_mwVintedVerwijderen",
  // De verwijderroutine van Marktplaats/2dehands — de eerste helft van elke
  // verversing. Zie mp-delete.html: die draait deze functie in een echte
  // browser tegen een nagebouwd "Mijn advertenties"-overzicht.
  "expandMp2dhOverview", "verwijderViaAdvertentiepagina", "bgDeleteMp2dh",
];

let out = "// AUTO-GENERATED by build.js — sliced verbatim out of extension/background.js\n";
// Losse variabelen waar de gesneden functies aan hangen.
for (const decl of ["let _laatsteVerwijderpagina", "const MP_FOTO_REGEL"]) {
  const m = bg.match(new RegExp("^" + decl + "[^\\n]*", "m"));
  if (m) out += m[0] + "\n";
}
out += "\n";
for (const name of wanted) {
  const re = new RegExp(`^(async )?function ${name}\\s*\\(`, "m");
  const m = bg.match(re);
  if (!m) { console.warn("not found:", name); continue; }
  out += bg.slice(m.index, bg.indexOf("{", m.index)) + sliceBody(m.index) + "\n\n";
}
// Vastgezet op de laatste versie VÓÓR de reparatie van 30-08-2026. Zou hier
// "HEAD" staan, dan vergelijkt de proef zichzelf zodra dit gecommit is en
// wordt het tegenbewijs stilletjes betekenisloos.
const VOOR_DE_REPARATIE = "0536966";

// TEGENBEWIJS. De versie van vóór de reparatie draait in dezelfde proef mee,
// onder de naam _oudBgDeleteMp2dh. Valt die niet om waar de nieuwe blijft
// staan, dan meet de proef niet wat hij beweert te meten.
try {
  const oud = require("child_process")
    .execSync("git show " + VOOR_DE_REPARATIE + ":extension/background.js", { cwd: path.join(__dirname, "../..") , maxBuffer: 1 << 26 })
    .toString();
  const bewaar = bg;
  const m = oud.match(/^async function bgDeleteMp2dh\s*\(/m);
  if (m) {
    // sliceBody leest uit de module-brede `bg`; even omleggen naar de oude tekst.
    const body = (function () {
      const echt = bg; // eslint-disable-line
      return sliceOut(oud, oud.indexOf("{", m.index));
    })();
    const kop = oud.slice(m.index, oud.indexOf("{", m.index));
    out += kop.replace("bgDeleteMp2dh", "_oudBgDeleteMp2dh") + body + "\n\n";
  }
} catch (e) { console.warn("oude versie niet opgehaald:", e.message); }

fs.writeFileSync(path.join(OUT, "mw-functions.js"), out);
console.log("harness built:", wanted.length, "main-world helpers +", 2, "content scripts");
